# Generated by Django 4.2.27 on 2025-12-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('muscle_group', models.CharField(blank=True, max_length=50, null=True)),
                ('equipment', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
